repos:
  # https://black.readthedocs.io/en/stable/version_control_integration.html
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  # https://pycqa.github.io/isort/docs/configuration/pre-commit/
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort (python)
